#!/bin/bash

#SBATCH --job-name=prg_job
#SBATCH --nodes=1
#SBATCH --ntasks=30
#SBATCH --time=1-00:00:00
#SBATCH --partition=RM
#SBATCH --output=slrum.%N.%j.out
#SBATCH --error=slrum.%N.%j.err
#SBATCH --mem=80GB


module load intel python intelmpi
source /ocean/projects/che240027p/shared/software/Team_RU/env.bash

mpirun -n 32 python  $1

